import{COLOR_PALETTE,HUE_NAMES,SHADE_LEVELS,getColorHex}from'../constants.js';
let _r=null,_h=-1,_sh=2;
export function initColorPicker(){const hc=document.getElementById('cp-hues');hc.innerHTML='';for(let h=0;h<25;h++){const b=document.createElement('div');b.className='cp-hue-btn';b.style.background=getColorHex(h,2);const n=document.createElement('span');n.className='cp-hue-name';n.textContent=HUE_NAMES[h];b.appendChild(n);b.onclick=()=>selH(h);hc.appendChild(b);}
document.getElementById('color-confirm').onclick=()=>{if(_r&&_h>=0)_r({hue:_h,shade:_sh});cls();};document.getElementById('color-cancel').onclick=cls;}
function selH(h){_h=h;document.querySelectorAll('.cp-hue-btn').forEach((e,i)=>e.classList.toggle('selected',i===h));bldS(h);upd();}
function bldS(h){const c=document.getElementById('cp-shades');c.innerHTML='';for(let s=0;s<5;s++){const b=document.createElement('div');b.className='cp-shade-btn';if(s===_sh)b.classList.add('selected');b.style.background=getColorHex(h,s);b.textContent=SHADE_LEVELS[s]>=0?`+${SHADE_LEVELS[s]}`:`${SHADE_LEVELS[s]}`;b.onclick=()=>{_sh=s;c.querySelectorAll('.cp-shade-btn').forEach((e,i)=>e.classList.toggle('selected',i===s));upd();};c.appendChild(b);}}
function upd(){if(_h<0)return;document.getElementById('cp-preview').style.background=getColorHex(_h,_sh);const sl=SHADE_LEVELS[_sh];document.getElementById('cp-name').textContent=`${HUE_NAMES[_h]} ${sl>=0?'+':''}${sl}`;}
function cls(){document.getElementById('color-picker-modal').hidden=true;_r=null;}
export function openColorPicker(cur){document.getElementById('color-picker-modal').hidden=false;_h=cur?cur.hue:-1;_sh=cur?cur.shade:2;document.querySelectorAll('.cp-hue-btn').forEach((e,i)=>e.classList.toggle('selected',i===_h));if(_h>=0){bldS(_h);upd();}else{document.getElementById('cp-shades').innerHTML='';document.getElementById('cp-preview').style.background='transparent';document.getElementById('cp-name').textContent='-';}return new Promise(r=>{_r=r;});}
