import{getState}from'../state.js';import{getColorHex,UNASSIGNED_COLOR}from'../constants.js';
export function getDisplayColor(tid,vl){const t=findDisplayTerritory(tid,vl);if(!t)return UNASSIGNED_COLOR;return getColorHex(t.color.hue,t.color.shade);}
export function findDisplayTerritory(tid,vl){const s=getState();let t=s.territories.get(tid);if(!t)return null;if(t.rank<=vl)return t;const v=new Set();let c=t;while(c){if(v.has(c.id))break;v.add(c.id);if(c.rank<=vl)return c;if(!c.parentId)break;c=s.territories.get(c.parentId);}return c||t;}
export function findBorderInfo(t1,t2,state,vl){if(t1===t2)return null;const c1=anc(t1,state),c2=anc(t2,state);let d=1;const ml=Math.min(c1.length,c2.length);for(let i=0;i<ml;i++){if(c1[i]!==c2[i]){d=i+1;break;}if(i===ml-1)d=ml+1;}if(c1.length!==c2.length&&d>ml)d=ml+1;const dt1=findDisplayTerritory(t1,vl),dt2=findDisplayTerritory(t2,vl);const vis=(!dt1&&!dt2)?false:(!dt1||!dt2)?true:dt1.id!==dt2.id;return{depth:d,visible:vis};}
function anc(tid,s){if(!tid)return[];const ch=[],v=new Set();let c=s.territories.get(tid);while(c){if(v.has(c.id))break;v.add(c.id);ch.unshift(c.id);if(!c.parentId)break;c=s.territories.get(c.parentId);}return ch;}
export function getChildren(tid,s){const r=[];for(const t of s.territories.values())if(t.parentId===tid)r.push(t);r.sort((a,b)=>(a.order||0)-(b.order||0));return r;}
export function getRoots(s){const r=[];for(const t of s.territories.values())if(!t.parentId)r.push(t);r.sort((a,b)=>(a.order||0)-(b.order||0));return r;}
export function isValidParent(t,pid,s){if(!pid)return true;const p=s.territories.get(pid);if(!p||p.rank>=t.rank)return false;const v=new Set();let c=p;while(c){if(c.id===t.id)return false;if(v.has(c.id))break;v.add(c.id);c=c.parentId?s.territories.get(c.parentId):null;}return true;}
export function countCells(tid,s){let c=0;for(let y=0;y<s.mapHeight;y++)for(let x=0;x<s.mapWidth;x++)if(s.cells[y][x].territoryId===tid)c++;return c;}
